[phases.setup]
nixPkgs = [
  "nodejs",
  "jdk17",
  "gradle",
  "android-tools"
]

[phases.build]
cmds = [
  "echo Instalando herramientas...",
  "node --version",
  "java --version",
  "gradle --version",
  "npm install"
]